[project]
name = "xarray-dataclasses"
version = "1.9.1"
dependencies = [
    "numpy>=1.22,<3.0",
    "xarray>=2022.3,<2026.0",
    "typing-extensions~=4.0"
]

requires-python = ">=3.9,<3.14"
description = "xarray data creation by data classes"
authors = [
    {name="Akio Taniguchi", email="taniguchi@a.phys.nagoya-u.ac.jp"}
]
keywords = ["xarray", "dataclass", "dataarray", "dataset", "typing"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/astropenguin/xarray-dataclasses/"
repository = "https://github.com/astropenguin/xarray-dataclasses/"
documentation = "https://astropenguin.github.io/xarray-dataclasses/"

[project.optional-dependencies]
dev = [
    "black~=24.4",
    "myst-parser~=3.0",
    "pydata-sphinx-theme~=0.14",
    "pyright~=1.1",
    "pytest~=8.2",
    "sphinx~=7.1",
    "ipython~=8.12"
]

[tool.pyright]
reportImportCycles = "warning"
reportUnknownArgumentType = "warning"
reportUnknownMemberType = "warning"
reportUnknownVariableType = "warning"
typeCheckingMode = "strict"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
