name: GitHub Pages

on:
  release:
    types:
      - created

jobs:
  build-docs:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.49.0
          frozen: true

      - name: Install doc env
        run: pixi install -a

      - name: Build documentation.
        run: |
          pixi run -e dev doc_build
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          force_orphan: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build
