name: GitHub Pages

on:
  release:
    types:
      - created

jobs:
  job:
    name: GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install project dependencies
        run: pip install -e ".[dev]"
      - name: Build docs
        run: python -m sphinx -b html docs docs/_build
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          force_orphan: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build
