name: Test documentation build

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.49.0
          frozen: true
      - name: Test build documentation
        run: |
          pixi run -e dev doc_build
